### ISSUE TITLE
No login code?

### ISSUE THREAD

**Issue by mittorn** [shinovon/mpgram-web#26]
Is it supposed to work now? It worked in January, but now no login code at all

**Comment by WunderWungiel** [comment]
@mittorn My instance works.
http://mp.wunderwungiel.pl

**Comment by Endedman** [comment]
@WunderWungiel My instance works too, but with BadGateway postcode

**Comment by Endedman** [comment]
@WunderWungiel

**Comment by R0ci0-V3rd3al** [comment]
works with 2fa. If you mean SMS, Telegram stopped starting via SMS if you don't use Google Play with the official or third-party app. by email or by another login works if you already have it configured

**Comment by WunderWungiel** [comment]
@Endedman Mine works without any problems, tried few days ago

**Comment by mittorn** [comment]
Telegram react works for me and sending login code to another telegram web instance, but mp.nnchan.ru does not, while logged in and working on another device. It asks login code when i attempting to login new device, but none appearing in service messages. Maybe it is rate-limited?

**Comment by mittorn** [comment]
@WunderWungiel, your instance works. It seems, nnchan is rate-limited
