### ISSUE TITLE
getUpdates doesn't return new message updates

### ISSUE THREAD

**Issue by CodeCraftsCanvas** [shinovon/mpgram-web#33]
Hi, very cool work so far, can you help me with 1 issue please?
I'm calling $updates = $MP->getUpdates(['offset' => $offset + 1, 'limit' => 100, 'timeout' => 1]);
it does return status but it doesnt return new message etc.
can you please guide me what I'm doing wrong?

**Comment by shinovon** [comment]
You should first find last update id by doing that in loop, then put it in offset param to get new updates

**Comment by CodeCraftsCanvas** [comment]
Sorted this but facing another issue.
can you tell me how can I add new account?
