### ISSUE TITLE
How to fix this?

### ISSUE THREAD

**Issue by FleshkaUsbTypeC** [shinovon/mpgram-web#54]
Im trying to sign in (in my instance) but i receiving this error 
Fatal error: Uncaught ErrorException: require_once(vendor/autoload.php): Failed to open stream: No such file or directory in /var/www/mpgram/mp.php:836 Stack trace: #0 /var/www/mpgram/mp.php(836): exceptions_error_handler() #1 /var/www/mpgram/mp.php(836): require_once() #2 /var/www/mpgram/login.php(207): MP::getMadelineAPI() #3 {main} thrown in /var/www/mpgram/mp.php on line 836

**Comment by FleshkaUsbTypeC** [comment]
Can't it be fix via Docker desktop?

**Comment by FleshkaUsbTypeC** [comment]
> follow manual deployment guide

Can't it be done via Docker desktop?

**Comment by shinovon** [comment]
> vendor/autoload.php
You're missing composer

**Comment by FleshkaUsbTypeC** [comment]
> follow manual deployment guide

Can't it be done via Docker desktop?

**Comment by FleshkaUsbTypeC** [comment]
> > vendor/autoload.php
> 
> You're missing composer

![image](https://github.com/shinovon/mpgram-web/assets/120157157/3cb01c6d-b2eb-4734-9cee-dd53b7dfd3ed)
What should I do if my compositor turns off automatically?

**Comment by shinovon** [comment]
Is it VPS/VDS?

**Comment by Feodor0090** [comment]
Setup WSL2 and use proper docker, that _may_ simplify things
