### ISSUE TITLE
Settings are not saving since moved to php session

### ISSUE THREAD

**Issue by shinovon** [shinovon/mpgram-web#57]

**Comment by nallion** [comment]
Have same problem, settings reset after 2-3 hours. Btw, i use old commit with settings in coockies in production.

**Comment by VictorFilimonov** [comment]
This happen when I using opera mini. In other browsers all ok.

**Comment by shinovon** [comment]
May be fixed by editing this value in php.ini to something larger
![image](https://github.com/shinovon/mpgram-web/assets/43963888/ed4bbc9f-321c-4c11-b842-3ffebf1e4980)
needs to be tested

**Comment by shinovon** [comment]
seems to be fixed with solution above, not closing until php sessions are dropped

**Comment by nallion** [comment]
Yes, fixed by solution above.

**Comment by VictorFilimonov** [comment]
@nallion @shinovon, let's close issue as completed

**Comment by shinovon** [comment]
probably won't be worked on for ever
