### ISSUE TITLE
images broken in docker, ubuntu 22.04

### ISSUE THREAD

**Issue by shadedclip** [shinovon/mpgram-web#81]
hi,
i have instance running on docker on kubuntu 22.04, i have tried both with and without lottie-converter and made sure that the bash declaration is at the top, and ffmpeg is in the $path but images are broken. when i click on the broken image and open it, i get this error:

Error: Call to undefined function imagecreatefromstring() in /var/www/mpgram/file.php:174
Stack trace:
#0 {main}

what should i do?

**Comment by shinovon** [comment]
you are missing php-gd extension

**Comment by shadedclip** [comment]
i have installed php-gd with apt, and rebuilt the container but they are still giving the same error. sorry if i'm missing something here, but how can i enable it?

**Comment by shadedclip** [comment]
SOLVED: i had to add this to `mpgram-web/docker/mpgram_web/Dockerfile` before the apt script 
(`
RUN apt-get update \
    && apt-get -y --no-install-recommends install \
    php8.3-mbstring \
    ...
` ) runs :

```dockerfile
RUN apt-get update \
    && apt-get install -y gnupg curl \
    && curl -fsSL https://packages.sury.org/php/apt.gpg | gpg --dearmor -o /usr/share/keyrings/php.gpg \
    && echo "deb [signed-by=/usr/share/keyrings/php.gpg] https://packages.sury.org/php/ bullseye main" > /etc/apt/sources.list.d/php.list \
    && apt-get update \
    && apt-get install -y php8.3-gd

```

**Comment by dariolob** [comment]
> SOLVED: i had to add this to `mpgram-web/docker/mpgram_web/Dockerfile` before the apt script (`RUN apt-get update \ && apt-get -y --no-install-recommends install \ php8.3-mbstring \ ...` ) runs :
> 
> RUN apt-get update \
>     && apt-get install -y gnupg curl \
>     && curl -fsSL https://packages.sury.org/php/apt.gpg | gpg --dearmor -o /usr/share/keyrings/php.gpg \
>     && echo "deb [signed-by=/usr/share/keyrings/php.gpg] https://packages.sury.org/php/ bullseye main" > /etc/apt/sources.list.d/php.list \
>     && apt-get update \
>     && apt-get install -y php8.3-gd

This configuration change doesn't seem to help in my case :( I've rebuilt the docker image using
`sudo docker-compose build --no-cache`
and then for good measure (maybe overkill) re-upped with:
`sudo docker-compose up --build -d --force-recreate --remove-orphans --always-recreate-deps`

But still no images whatsoever, I just get the same error message "Call to undefined function imagecreatefromstring()..."

Do you have any suggestion?
